python ../scimaf_dir.py --db agnddf_v1.5_10yrs.db
python ../scimaf_dir.py --db alt_dust_v1.5_10yrs.db
python ../scimaf_dir.py --db alt_roll_mod2_dust_sdf_0.20_v1.5_10yrs.db
python ../scimaf_dir.py --db baseline_2snaps_v1.5_10yrs.db
python ../scimaf_dir.py --db baseline_v1.5_10yrs.db
python ../scimaf_dir.py --db bulges_bs_v1.5_10yrs.db
python ../scimaf_dir.py --db bulges_bulge_wfd_v1.5_10yrs.db
python ../scimaf_dir.py --db bulges_cadence_bs_v1.5_10yrs.db
python ../scimaf_dir.py --db bulges_cadence_bulge_wfd_v1.5_10yrs.db
python ../scimaf_dir.py --db bulges_cadence_i_heavy_v1.5_10yrs.db
python ../scimaf_dir.py --db bulges_i_heavy_v1.5_10yrs.db
python ../scimaf_dir.py --db daily_ddf_v1.5_10yrs.db
python ../scimaf_dir.py --db dcr_nham1_ugri_v1.5_10yrs.db
python ../scimaf_dir.py --db dcr_nham1_ugr_v1.5_10yrs.db
python ../scimaf_dir.py --db dcr_nham1_ug_v1.5_10yrs.db
python ../scimaf_dir.py --db dcr_nham2_ugri_v1.5_10yrs.db
python ../scimaf_dir.py --db dcr_nham2_ugr_v1.5_10yrs.db
python ../scimaf_dir.py --db dcr_nham2_ug_v1.5_10yrs.db
python ../scimaf_dir.py --db descddf_v1.5_10yrs.db
python ../scimaf_dir.py --db filterdist_indx1_v1.5_10yrs.db
python ../scimaf_dir.py --db filterdist_indx2_v1.5_10yrs.db
python ../scimaf_dir.py --db filterdist_indx3_v1.5_10yrs.db
python ../scimaf_dir.py --db filterdist_indx4_v1.5_10yrs.db
python ../scimaf_dir.py --db filterdist_indx5_v1.5_10yrs.db
python ../scimaf_dir.py --db filterdist_indx6_v1.5_10yrs.db
python ../scimaf_dir.py --db filterdist_indx7_v1.5_10yrs.db
python ../scimaf_dir.py --db filterdist_indx8_v1.5_10yrs.db
python ../scimaf_dir.py --db footprint_add_mag_cloudsv1.5_10yrs.db
python ../scimaf_dir.py --db footprint_big_sky_dustv1.5_10yrs.db
python ../scimaf_dir.py --db footprint_big_sky_nouiyv1.5_10yrs.db
python ../scimaf_dir.py --db footprint_big_skyv1.5_10yrs.db
python ../scimaf_dir.py --db footprint_big_wfdv1.5_10yrs.db
python ../scimaf_dir.py --db footprint_bluer_footprintv1.5_10yrs.db
python ../scimaf_dir.py --db footprint_gp_smoothv1.5_10yrs.db
python ../scimaf_dir.py --db footprint_newAv1.5_10yrs.db
python ../scimaf_dir.py --db footprint_newBv1.5_10yrs.db
python ../scimaf_dir.py --db footprint_no_gp_northv1.5_10yrs.db
python ../scimaf_dir.py --db footprint_standard_goalsv1.5_10yrs.db
python ../scimaf_dir.py --db footprint_stuck_rollingv1.5_10yrs.db
python ../scimaf_dir.py --db goodseeing_gi_v1.5_10yrs.db
python ../scimaf_dir.py --db goodseeing_gri_v1.5_10yrs.db
python ../scimaf_dir.py --db goodseeing_griz_v1.5_10yrs.db
python ../scimaf_dir.py --db goodseeing_gz_v1.5_10yrs.db
python ../scimaf_dir.py --db goodseeing_i_v1.5_10yrs.db
python ../scimaf_dir.py --db greedy_footprint_v1.5_10yrs.db
python ../scimaf_dir.py --db rolling_mod2_sdf_0.10_v1.5_10yrs.db
python ../scimaf_dir.py --db rolling_mod2_sdf_0.20_v1.5_10yrs.db
python ../scimaf_dir.py --db rolling_mod3_sdf_0.10_v1.5_10yrs.db
python ../scimaf_dir.py --db rolling_mod3_sdf_0.20_v1.5_10yrs.db
python ../scimaf_dir.py --db rolling_mod6_sdf_0.10_v1.5_10yrs.db
python ../scimaf_dir.py --db rolling_mod6_sdf_0.20_v1.5_10yrs.db
python ../scimaf_dir.py --db roll_mod2_dust_sdf_0.20_v1.5_10yrs.db
python ../scimaf_dir.py --db short_exp_2ns_1expt_v1.5_10yrs.db
python ../scimaf_dir.py --db short_exp_2ns_5expt_v1.5_10yrs.db
python ../scimaf_dir.py --db short_exp_5ns_1expt_v1.5_10yrs.db
python ../scimaf_dir.py --db short_exp_5ns_5expt_v1.5_10yrs.db
python ../scimaf_dir.py --db spiders_v1.5_10yrs.db
python ../scimaf_dir.py --db third_obs_pt120v1.5_10yrs.db
python ../scimaf_dir.py --db third_obs_pt15v1.5_10yrs.db
python ../scimaf_dir.py --db third_obs_pt30v1.5_10yrs.db
python ../scimaf_dir.py --db third_obs_pt45v1.5_10yrs.db
python ../scimaf_dir.py --db third_obs_pt60v1.5_10yrs.db
python ../scimaf_dir.py --db third_obs_pt90v1.5_10yrs.db
python ../scimaf_dir.py --db twilight_neo_mod1_v1.5_10yrs.db
python ../scimaf_dir.py --db twilight_neo_mod2_v1.5_10yrs.db
python ../scimaf_dir.py --db twilight_neo_mod3_v1.5_10yrs.db
python ../scimaf_dir.py --db twilight_neo_mod4_v1.5_10yrs.db
python ../scimaf_dir.py --db u60_v1.5_10yrs.db
python ../scimaf_dir.py --db var_expt_v1.5_10yrs.db
python ../scimaf_dir.py --db wfd_depth_scale0.65_noddf_v1.5_10yrs.db
python ../scimaf_dir.py --db wfd_depth_scale0.65_v1.5_10yrs.db
python ../scimaf_dir.py --db wfd_depth_scale0.70_noddf_v1.5_10yrs.db
python ../scimaf_dir.py --db wfd_depth_scale0.70_v1.5_10yrs.db
python ../scimaf_dir.py --db wfd_depth_scale0.75_noddf_v1.5_10yrs.db
python ../scimaf_dir.py --db wfd_depth_scale0.75_v1.5_10yrs.db
python ../scimaf_dir.py --db wfd_depth_scale0.80_noddf_v1.5_10yrs.db
python ../scimaf_dir.py --db wfd_depth_scale0.80_v1.5_10yrs.db
python ../scimaf_dir.py --db wfd_depth_scale0.85_noddf_v1.5_10yrs.db
python ../scimaf_dir.py --db wfd_depth_scale0.85_v1.5_10yrs.db
python ../scimaf_dir.py --db wfd_depth_scale0.90_noddf_v1.5_10yrs.db
python ../scimaf_dir.py --db wfd_depth_scale0.90_v1.5_10yrs.db
python ../scimaf_dir.py --db wfd_depth_scale0.95_noddf_v1.5_10yrs.db
python ../scimaf_dir.py --db wfd_depth_scale0.95_v1.5_10yrs.db
python ../scimaf_dir.py --db wfd_depth_scale0.99_noddf_v1.5_10yrs.db
python ../scimaf_dir.py --db wfd_depth_scale0.99_v1.5_10yrs.db
python ../glance_dir.py --db agnddf_v1.5_10yrs.db
python ../glance_dir.py --db alt_dust_v1.5_10yrs.db
python ../glance_dir.py --db alt_roll_mod2_dust_sdf_0.20_v1.5_10yrs.db
python ../glance_dir.py --db baseline_2snaps_v1.5_10yrs.db
python ../glance_dir.py --db baseline_v1.5_10yrs.db
python ../glance_dir.py --db bulges_bs_v1.5_10yrs.db
python ../glance_dir.py --db bulges_bulge_wfd_v1.5_10yrs.db
python ../glance_dir.py --db bulges_cadence_bs_v1.5_10yrs.db
python ../glance_dir.py --db bulges_cadence_bulge_wfd_v1.5_10yrs.db
python ../glance_dir.py --db bulges_cadence_i_heavy_v1.5_10yrs.db
python ../glance_dir.py --db bulges_i_heavy_v1.5_10yrs.db
python ../glance_dir.py --db daily_ddf_v1.5_10yrs.db
python ../glance_dir.py --db dcr_nham1_ugri_v1.5_10yrs.db
python ../glance_dir.py --db dcr_nham1_ugr_v1.5_10yrs.db
python ../glance_dir.py --db dcr_nham1_ug_v1.5_10yrs.db
python ../glance_dir.py --db dcr_nham2_ugri_v1.5_10yrs.db
python ../glance_dir.py --db dcr_nham2_ugr_v1.5_10yrs.db
python ../glance_dir.py --db dcr_nham2_ug_v1.5_10yrs.db
python ../glance_dir.py --db descddf_v1.5_10yrs.db
python ../glance_dir.py --db filterdist_indx1_v1.5_10yrs.db
python ../glance_dir.py --db filterdist_indx2_v1.5_10yrs.db
python ../glance_dir.py --db filterdist_indx3_v1.5_10yrs.db
python ../glance_dir.py --db filterdist_indx4_v1.5_10yrs.db
python ../glance_dir.py --db filterdist_indx5_v1.5_10yrs.db
python ../glance_dir.py --db filterdist_indx6_v1.5_10yrs.db
python ../glance_dir.py --db filterdist_indx7_v1.5_10yrs.db
python ../glance_dir.py --db filterdist_indx8_v1.5_10yrs.db
python ../glance_dir.py --db footprint_add_mag_cloudsv1.5_10yrs.db
python ../glance_dir.py --db footprint_big_sky_dustv1.5_10yrs.db
python ../glance_dir.py --db footprint_big_sky_nouiyv1.5_10yrs.db
python ../glance_dir.py --db footprint_big_skyv1.5_10yrs.db
python ../glance_dir.py --db footprint_big_wfdv1.5_10yrs.db
python ../glance_dir.py --db footprint_bluer_footprintv1.5_10yrs.db
python ../glance_dir.py --db footprint_gp_smoothv1.5_10yrs.db
python ../glance_dir.py --db footprint_newAv1.5_10yrs.db
python ../glance_dir.py --db footprint_newBv1.5_10yrs.db
python ../glance_dir.py --db footprint_no_gp_northv1.5_10yrs.db
python ../glance_dir.py --db footprint_standard_goalsv1.5_10yrs.db
python ../glance_dir.py --db footprint_stuck_rollingv1.5_10yrs.db
python ../glance_dir.py --db goodseeing_gi_v1.5_10yrs.db
python ../glance_dir.py --db goodseeing_gri_v1.5_10yrs.db
python ../glance_dir.py --db goodseeing_griz_v1.5_10yrs.db
python ../glance_dir.py --db goodseeing_gz_v1.5_10yrs.db
python ../glance_dir.py --db goodseeing_i_v1.5_10yrs.db
python ../glance_dir.py --db greedy_footprint_v1.5_10yrs.db
python ../glance_dir.py --db rolling_mod2_sdf_0.10_v1.5_10yrs.db
python ../glance_dir.py --db rolling_mod2_sdf_0.20_v1.5_10yrs.db
python ../glance_dir.py --db rolling_mod3_sdf_0.10_v1.5_10yrs.db
python ../glance_dir.py --db rolling_mod3_sdf_0.20_v1.5_10yrs.db
python ../glance_dir.py --db rolling_mod6_sdf_0.10_v1.5_10yrs.db
python ../glance_dir.py --db rolling_mod6_sdf_0.20_v1.5_10yrs.db
python ../glance_dir.py --db roll_mod2_dust_sdf_0.20_v1.5_10yrs.db
python ../glance_dir.py --db short_exp_2ns_1expt_v1.5_10yrs.db
python ../glance_dir.py --db short_exp_2ns_5expt_v1.5_10yrs.db
python ../glance_dir.py --db short_exp_5ns_1expt_v1.5_10yrs.db
python ../glance_dir.py --db short_exp_5ns_5expt_v1.5_10yrs.db
python ../glance_dir.py --db spiders_v1.5_10yrs.db
python ../glance_dir.py --db third_obs_pt120v1.5_10yrs.db
python ../glance_dir.py --db third_obs_pt15v1.5_10yrs.db
python ../glance_dir.py --db third_obs_pt30v1.5_10yrs.db
python ../glance_dir.py --db third_obs_pt45v1.5_10yrs.db
python ../glance_dir.py --db third_obs_pt60v1.5_10yrs.db
python ../glance_dir.py --db third_obs_pt90v1.5_10yrs.db
python ../glance_dir.py --db twilight_neo_mod1_v1.5_10yrs.db
python ../glance_dir.py --db twilight_neo_mod2_v1.5_10yrs.db
python ../glance_dir.py --db twilight_neo_mod3_v1.5_10yrs.db
python ../glance_dir.py --db twilight_neo_mod4_v1.5_10yrs.db
python ../glance_dir.py --db u60_v1.5_10yrs.db
python ../glance_dir.py --db var_expt_v1.5_10yrs.db
python ../glance_dir.py --db wfd_depth_scale0.65_noddf_v1.5_10yrs.db
python ../glance_dir.py --db wfd_depth_scale0.65_v1.5_10yrs.db
python ../glance_dir.py --db wfd_depth_scale0.70_noddf_v1.5_10yrs.db
python ../glance_dir.py --db wfd_depth_scale0.70_v1.5_10yrs.db
python ../glance_dir.py --db wfd_depth_scale0.75_noddf_v1.5_10yrs.db
python ../glance_dir.py --db wfd_depth_scale0.75_v1.5_10yrs.db
python ../glance_dir.py --db wfd_depth_scale0.80_noddf_v1.5_10yrs.db
python ../glance_dir.py --db wfd_depth_scale0.80_v1.5_10yrs.db
python ../glance_dir.py --db wfd_depth_scale0.85_noddf_v1.5_10yrs.db
python ../glance_dir.py --db wfd_depth_scale0.85_v1.5_10yrs.db
python ../glance_dir.py --db wfd_depth_scale0.90_noddf_v1.5_10yrs.db
python ../glance_dir.py --db wfd_depth_scale0.90_v1.5_10yrs.db
python ../glance_dir.py --db wfd_depth_scale0.95_noddf_v1.5_10yrs.db
python ../glance_dir.py --db wfd_depth_scale0.95_v1.5_10yrs.db
python ../glance_dir.py --db wfd_depth_scale0.99_noddf_v1.5_10yrs.db
python ../glance_dir.py --db wfd_depth_scale0.99_v1.5_10yrs.db

