python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs1.5/dcr/dcr.py --filters ug --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs1.5/dcr
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs1.5/dcr/dcr.py --filters ugr --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs1.5/dcr
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs1.5/dcr/dcr.py --filters ugri --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs1.5/dcr
