python ../scimaf_dir.py --db barebonesv1.5_10yrs.db
python ../scimaf_dir.py --db mw_heavy_v1.5_10yrs.db
python ../scimaf_dir.py --db baseline_nexp1_v1.5_10yrs.db                   
python ../scimaf_dir.py --db rolling_exgal_mod2_dust_sdf_0.20_v1.5_10yrs.db
python ../scimaf_dir.py --db baseline_nexp2_v1.5_10yrs.db                   
python ../scimaf_dir.py --db ss_heavy_v1.5_10yrs.db
python ../scimaf_dir.py --db ddf_heavy_v1.5_10yrs.db                        
python ../scimaf_dir.py --db dm_heavy_v1.5_10yrs.db
